version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_movie_management
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - .docker/mysql/data:/var/lib/mysql