CREATE TABLE `ticket_info` (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  movie_name VARCHAR(255) NOT NULL,
  movie_date DATE NOT NULL,
  movie_time VARCHAR(20) NOT NULL,
  ticket_prize DOUBLE NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE `payment_info` (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  account_no VARCHAR(255) NOT NULL,
  amount DOUBLE NOT NULL,
  card_type VARCHAR(50) NOT NULL,
  ticket_id BIGINT NOT NULL,
  PRIMARY KEY (id)
);