springdoc:
  swagger-ui:
    path: /api-cdc
  api-docs:
    path: /api-docs

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db-api-cdc?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG